# The specification version of docker-compose
version: "3.9"
# The collection of applications composing this service
services:

  # This container acts as an Apache webserver
  app:
    build:
      context: ./bin/apache2
    container_name: app
    restart: always
    # The external port mapping to internal port mapping
    ports:
      - ${HOST_MACHINE_UNSECURE_HOST_PORT}:80 # expose chosen port on host and sent to 80 in container
      - ${HOST_MACHINE_SECURE_HOST_PORT}:443
    # The external directory location to map to an internal location
    volumes:
      - ${PROJECT_ROOT-./www}:/var/www/html/wetube
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT-/var/www/html}
    networks:
      main:
        aliases:
          - wetube.test

  # This container contains Nodejs dependencies that take care of the JS builds
  node:
    build:
      context: ./bin/node
    container_name: node
    restart: always
    command: bash -c "cd /usr/app/wetube && npm install --ignore-engines && npm start"
    tty: true
    ports:
      - "3000:3000"
    links:
      - "app:wetube.test"
    networks:
      - main
    volumes:
      - ${PROJECT_ROOT-./www}:/usr/app/wetube
    working_dir: /usr/app
    environment:
      HOST: 0.0.0.0

networks:
  main: